apiVersion: v1
kind: ServiceAccount

metadata:
  name: webapp-reader
  namespace: webapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: pod-reader
  namespace: webapp

rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: webapp-reader-binding
  namespace: webapp

subjects:
  - kind: ServiceAccount
    name: webapp-reader
    namespace: webapp

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader