apiVersion: v1
kind: Secret

metadata:
  name: webapp-secret
  namespace: webapp
  labels:
    app: webapp

type: Opaque

stringData:
  DB_PASSWORD: "ChangeMe_DemoOnly_42"
  API_TOKEN: "tok_demo_a1b2c3_NE_PAS_COMMITTER"